# Generated by Django 5.0.3 on 2024-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_producto_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_en_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
