# Generated by Django 5.0.3 on 2024-04-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_producto_foto_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
        migrations.AddField(
            model_name='producto',
            name='fotoLink',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
