# Generated by Django 5.0.3 on 2024-08-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_precio_producto_precio_arriendo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_en_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
