# Generated by Django 5.0.3 on 2024-04-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_producto_foto_producto_fotolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotoLink',
            field=models.URLField(default='https://www.google.com', max_length=255),
        ),
    ]
