# Generated by Django 5.0.3 on 2024-04-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_producto_fotolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotoLink',
            field=models.TextField(max_length=1000000),
        ),
    ]
